# Generated by Django 3.2.12 on 2023-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
