# Generated by Django 4.1.6 on 2023-02-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
